export const products = [
  {
    id: 1,
    title: "Smartphone",
    desc: "Latest model with high performance and long battery life.",
    price: 789,
    colors: ["black", "blue"],
    sizes: [],
    categories: ["electronics"],
    image: "/products/smartphone.jpg",
    createdAt: "01/01/2024",
  },
  {
    id: 2,
    title: "Running Shoes",
    desc: "Comfortable and durable running shoes for daily workouts.",
    price: 999,
    colors: ["black", "white"],
    sizes: ["7", "8", "9", "10"],
    categories: ["clothing"],
    image: "/products/shoes.jpg",
    createdAt: "15/02/2024",
  },
  {
    id: 3,
    title: "Backpack",
    desc: "Spacious and ergonomic backpack for everyday use.",
    price: 700,
    colors: ["black", "grey"],
    sizes: [],
    categories: ["home"],
    image: "/products/bag.jpg",
    createdAt: "10/03/2024",
  },
  {
    id: 4,
    title: "Wireless Headphones",
    desc: "Noise-cancelling wireless headphones with clear audio.",
    price: 999,
    colors: ["white", "black"],
    sizes: [],
    categories: ["electronics"],
    image: "/products/headphones.jpg",
    createdAt: "20/03/2024",
  },
  {
    id: 5,
    title: "Men Black Hoodie",
    desc: "A warm and stylish hoodie perfect for casual wear.",
    price: 899,
    colors: ["black"],
    sizes: ["m", "l"],
    categories: ["clothing"],
    image: "/products/hoodie.jpg",
    createdAt: "05/11/2023",
  },
  {
    id: 6,
    title: "Women Brown Kurti",
    desc: "Traditional and elegant design with modern comfort.",
    price: 799,
    colors: ["brown"],
    sizes: ["s", "m", "l"],
    categories: ["clothing"],
    image: "/products/kurti.jpg",
    createdAt: "15/03/2024",
  },
  {
    id: 7,
    title: "Smartwatch",
    desc: "Track your fitness and notifications on the go.",
    price: 499,
    colors: ["black"],
    sizes: [],
    categories: ["electronics"],
    image: "/products/smartwatch.jpg",
    createdAt: "10/04/2024",
  },
  {
    id: 8,
    title: "Home Decor Lamp",
    desc: "Stylish table lamp to enhance your living space.",
    price: 799,
    colors: ["white"],
    sizes: [],
    categories: ["home"],
    image: "/products/lamp.jpg",
    createdAt: "01/05/2024",
  }
];
